"""Initial database

Revision ID: 2ea86f0445a5
Revises: 
Create Date: 2020-10-03 17:16:15.565867

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2ea86f0445a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('first_name', table_name='users')
    op.drop_index('last_name', table_name='users')
    op.drop_index('password', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('password', 'users', ['password'], unique=True)
    op.create_index('last_name', 'users', ['last_name'], unique=True)
    op.create_index('first_name', 'users', ['first_name'], unique=True)
    # ### end Alembic commands ###
